---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: oel64-64
    driver:
      box: oel64-64
      box_url: https://storage.us2.oraclecloud.com/v1/istoilis-istoilis/vagrant/oel64-64.box

suites:
  - name: default
    run_list:
      - recipe[ice_localrepo::default]
      - recipe[ice_nginx::default]
    attributes:
